
# Site settings
title: Portfolio By Aurora Feng
email: jieyi.feng.china@gmail.com
description: "这里是冯洁怡的作品集"

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
